Repository ygor-sena/42cursus-miniRT, pull requests merged in 2023-04, with the labels that each got.

#5 feat: add ray-sphere intersection
  Makefile
  include/rays.h
  include/shapes.h
  include/tuples.h
  src/rays/rays.c
  src/shapes/intersections.c
  src/shapes/spheres.c
  tests/Makefile
  tests/test_intersections.c
  tests/test_rays.c
  tests/test_spheres.c
  tests/utils.c
  tests/utils.h
Labels: ✨ enhancement

#7 refactor: point_light returns a block of memory
  include/lights.h
  src/lights/lights.c
  tests/colors
  tests/intersections
  tests/lights
  tests/materials
  tests/matrices
  tests/rays
  tests/spheres
  tests/test_lights.c
  tests/transformations
  tests/tuples
Labels: ✨ enhancement

#10 fix: uninitialized windows on workspace's environment
  exercises/ch02/projectile.c
Labels: 🐛 bug

#11 test: add testing exercises of chapters 5 and 6
  exercises/Makefile
  exercises/ch02/projectile.c
  exercises/ch05/sun.c
  exercises/ch06/volume.c
  include/canvas.h
  src/canvas/canvas.c
  src/main.c
Labels: documentation, ✨ enhancement

#14 feat: add functions for camera manipulation
  .gitignore
  Makefile
  exercises/Makefile
  exercises/ch02/projectile.c
  exercises/ch05/sun.c
  exercises/ch06/volume.c
  exercises/ch07/background.c
  include/camera.h
  include/canvas.h
  include/helpers.h
  include/lights.h
  include/materials.h
  include/matrices.h
  include/shapes.h
  include/tuples.h
  include/world.h
  src/camera/camera.c
  src/camera/view_transform.c
  src/canvas/canvas.c
  src/canvas/controls.c
  src/canvas/render.c
  src/main.c
  src/shapes/spheres.c
  src/world/world.c
  tests/Makefile
  tests/test_camera.c
  tests/test_lights.c
  tests/test_view_transform.c
  tests/utils.c
  tests/utils.h
Labels: ✨ enhancement

#13 docs: adds modules' description of used functions
  include/canvas.h
  include/helpers.h
  include/matrices.h
  include/rays.h
  include/shapes.h
  include/tuples.h
  include/world.h
Labels: documentation

#17 refactor: create abstract parent for shapes
  Makefile
  include/shapes.h
  include/world.h
  src/main.c
  src/shapes/intersections.c
  src/shapes/shapes.c
  src/shapes/spheres.c
  src/world/shadows.c
  src/world/world.c
  tests/Makefile
  tests/test_intersections.c
  tests/test_shapes.c
  tests/test_spheres.c
  tests/test_world.c
  tests/utils.c
  tests/utils.h
Labels: refactor
