Repository ygor-sena/42cursus-miniRT, pull requests merged in 2023-05, with the labels that each got.

#20 feat: add cylinders to shapes' rendering collection
  Makefile
  include/helpers.h
  include/shapes.h
  src/helpers/guards.c
  src/shapes/cylinders.c
  src/shapes/intersections.c
  src/shapes/spheres.c
  tests/Makefile
  tests/test_cylinders.c
  tests/utils.c
Labels: ✨ enhancement

#23 feat: implement multiple light points
  include/matrices.h
  include/parser.h
  include/tuples.h
  include/world.h
  src/camera/view_transform.c
  src/matrices/mx_attributes.c
  src/matrices/mx_operations.c
  src/matrices/mx_rotations.c
  src/matrices/mx_transformations.c
  src/matrices/mx_utils.c
  src/parser/parse_ambient.c
  src/parser/parse_basic.c
  src/parser/parse_grouped.c
  src/parser/parse_shapes.c
  src/parser/parse_utils.c
  src/parser/scanner.c
  src/shapes/planes.c
  src/tuples/basic_math.c
  src/tuples/colors.c
  src/tuples/models.c
  src/tuples/vector_math.c
  src/world/shadows.c
  src/world/world.c
  tests/test_cylinders.c
  tests/test_matrices.c
  tests/test_parser.c
  tests/test_scanner.c
  tests/test_view_transform.c
  tests/test_world.c
Labels: ✨ enhancement, refactor

#25 docs: add up-to-date function description of 8 header files
  include/camera.h
  include/canvas.h
  include/lights.h
  include/materials.h
  include/matrices.h
  include/rays.h
  include/shapes.h
  include/world.h
  src/canvas/render.c
  src/shapes/cones.c
  src/shapes/cylinders.c
  src/shapes/discriminants.c
  src/shapes/spheres.c
  src/world/world.c
  tests/utils.h
Labels: documentation
