Repository ygor-sena/42cursus-miniRT, pull requests merged in 2023-06, with the labels that each got.

#28 feat: handle bump map textures
  Makefile
  include/canvas.h
  include/helpers.h
  include/parser.h
  include/patterns.h
  include/shapes.h
  src/canvas/render.c
  src/helpers/guards.c
  src/main.c
  src/parser/parse.c
  src/parser/parse_pattern.c
  src/parser/parse_textures.c
  src/patterns/bumpmap.c
  src/patterns/patterns.c
  src/shapes/cones.c
  src/shapes/cylinders.c
  src/shapes/planes.c
  src/shapes/spheres.c
  tests/test_cones.c
  tests/test_cylinders.c
Labels: ✨ enhancement, refactor

#30 fix(parser): check for denormalized vector
  include/parser.h
  src/parser/parse_ambient.c
  src/parser/parse_grouped.c
  src/parser/parse_shapes_1.c
  src/parser/parse_shapes_2.c
  src/parser/scanner.c
  src/parser/scanner_utils.c
  tests/test_parser.c
Labels: 🐛 bug, refactor

#32 docs(README): add finished readme file
  README.md
Labels: documentation

#34 feat(images): add image of Earth seen from space
  README.md
  images/img19.rt
Labels: ✨ enhancement

#35 docs(README): add minor style adjustments
  README.md
  src/matrices/mx_operations.c
Labels: documentation

#36 docs(README): add paragraph about doxygen creation
  README.md
Labels: documentation
